[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "harry-ml"
version = "0.0.1"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["src"]
